#spring.application.name=fineDust
#
#spring.datasource.jdbc-url=jdbc:mysql://localhost:3306/gyeonggi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.gangwon.datasource.jdbc-url=jdbc:mysql://localhost:3307/gangwon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.gangwon.datasource.username=root
#spring.gangwon.datasource.password=password
#spring.gangwon.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.chungcheong.datasource.jdbc-url=jdbc:mysql://localhost:3308/chungcheong?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.chungcheong.datasource.username=root
#spring.chungcheong.datasource.password=password
#spring.chungcheong.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.gyeongsang.datasource.jdbc-url=jdbc:mysql://localhost:3309/gyeongsang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.gyeongsang.datasource.username=root
#spring.gyeongsang.datasource.password=password
#spring.gyeongsang.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jeolla.datasource.jdbc-url=jdbc:mysql://localhost:3310/jeolla?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.jeolla.datasource.username=root
#spring.jeolla.datasource.password=password
#spring.jeolla.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jeju.datasource.jdbc-url=jdbc:mysql://localhost:3311/jeju?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#spring.jeju.datasource.username=root
#spring.jeju.datasource.password=password
#spring.jeju.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
#
## JPA and Hibernate Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#
#
#
## Encoding Configuration
#server.servlet.encoding.carset=UTF-8
#server.servlet.encoding.force=true
#server.servlet.encoding.enabled=true
#
## Profile Configuration
#spring.profiles.active=dev
#
## External API Configuration
#service.key=z%2F5j97wfXdV4OfQ1Ze%2FszF79mEXa4NL2O0CVaRm5J7D4mxFJJvqbR%2BLrgvwAv%2FTExOmAxygPZu6HDNc9SezHTw%3D%3D
spring:
  application:
    name: fineDust
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  gangwon:
    datasource:
      url: ${SPRING_GANGWON_DATASOURCE_URL}
      username: ${SPRING_GANGWON_DATASOURCE_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  chungcheong:
    datasource:
      url: ${SPRING_CHUNGCHEONG_DATASOURCE_URL}
      username: ${SPRING_CHUNGCHEONG_DATASOURCE_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  gyeongsang:
    datasource:
      url: ${SPRING_GYEONGSANG_DATASOURCE_URL}
      username: ${SPRING_GYEONGSANG_DATASOURCE_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jeolla:
    datasource:
      url: ${SPRING_JEOLLA_DATASOURCE_URL}
      username: ${SPRING_JEOLLA_DATASOURCE_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jeju:
    datasource:
      url: ${SPRING_JEJU_DATASOURCE_URL}
      username: ${SPRING_JEJU_DATASOURCE_USERNAME}
      password: ${MYSQL_ROOT_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
service:
  key: z%2F5j97wfXdV4OfQ1Ze%2FszF79mEXa4NL2O0CVaRm5J7D4mxFJJvqbR%2BLrgvwAv%2FTExOmAxygPZu6HDNc9SezHTw%3D%3D
