apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
    - port: 443
      targetPort: 443
  selector:
    app: ingress-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: fine-dust-service
spec:
  selector:
    app: fine-dust-app
  ports:
    - port: 8181
      targetPort: 8181
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fine-dust-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fine-dust.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fine-dust-service
                port:
                  number: 8181
