apiVersion: apps/v1
kind: Deployment
metadata:
  name: fine-dust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fine-dust-app
  template:
    metadata:
      labels:
        app: fine-dust-app
    spec:
      containers:
        - name: fine-dust-app
          image: kdonghwan/k8s_finedust_system:latest
          ports:
            - containerPort: 8181
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: fine-dust-config
          env:
            - name: SPRING_GYEONGGI_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fine-dust-app-secrets
                  key: SPRING_GYEONGGI_DATASOURCE_PASSWORD
            - name: SPRING_GANGWON_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fine-dust-app-secrets
                  key: SPRING_GANGWON_DATASOURCE_PASSWORD
            - name: SPRING_CHUNGCHEONG_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fine-dust-app-secrets
                  key: SPRING_CHUNGCHEONG_DATASOURCE_PASSWORD
            - name: SPRING_GYEONGSANG_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fine-dust-app-secrets
                  key: SPRING_GYEONGSANG_DATASOURCE_PASSWORD
            - name: SPRING_JEOLLA_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fine-dust-app-secrets
                  key: SPRING_JEOLLA_DATASOURCE_PASSWORD
            - name: SPRING_JEJU_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fine-dust-app-secrets
                  key: SPRING_JEJU_DATASOURCE_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8181
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8181
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
        - name: busybox
          image: alpine
          command: ['sh', '-c', 'apk add --no-cache curl && sleep 3600']
