apiVersion: apps/v1
kind: Deployment
metadata:
  name: fine-dust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fine-dust-app
  template:
    metadata:
      labels:
        app: fine-dust-app
    spec:
      containers:
        - name: fine-dust-app
          image: kdonghwan/k8s_finedust_system:latest
          ports:
            - containerPort: 8181
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: fine-dust-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_GANGWON_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_CHUNGCHEONG_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_GYEONGSANG_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_JEOLLA_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_JEJU_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8181
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8181
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fine-dust-service
spec:
  type: LoadBalancer
  selector:
    app: fine-dust-app
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 8181
