apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-gyeonggi
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gyeonggi"
          volumeMounts:
            - name: mysql-gyeonggi-storage
              mountPath: /var/lib/mysql
        - name: mysql-gangwon
          image: mysql:5.7
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gangwon"
          volumeMounts:
            - name: mysql-gangwon-storage
              mountPath: /var/lib/mysql
        - name: mysql-chungcheong
          image: mysql:5.7
          ports:
            - containerPort: 3308
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "chungcheong"
          volumeMounts:
            - name: mysql-chungcheong-storage
              mountPath: /var/lib/mysql
        - name: mysql-gyeongsang
          image: mysql:5.7
          ports:
            - containerPort: 3309
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gyeongsang"
          volumeMounts:
            - name: mysql-gyeongsang-storage
              mountPath: /var/lib/mysql
        - name: mysql-jeolla
          image: mysql:5.7
          ports:
            - containerPort: 3310
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "jeolla"
          volumeMounts:
            - name: mysql-jeolla-storage
              mountPath: /var/lib/mysql
        - name: mysql-jeju
          image: mysql:5.7
          ports:
            - containerPort: 3311
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "jeju"
          volumeMounts:
            - name: mysql-jeju-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-gyeonggi-storage
          persistentVolumeClaim:
            claimName: mysql-gyeonggi-pvc
        - name: mysql-gangwon-storage
          persistentVolumeClaim:
            claimName: mysql-gangwon-pvc
        - name: mysql-chungcheong-storage
          persistentVolumeClaim:
            claimName: mysql-chungcheong-pvc
        - name: mysql-gyeongsang-storage
          persistentVolumeClaim:
            claimName: mysql-gyeongsang-pvc
        - name: mysql-jeolla-storage
          persistentVolumeClaim:
            claimName: mysql-jeolla-pvc
        - name: mysql-jeju-storage
          persistentVolumeClaim:
            claimName: mysql-jeju-pvc
