apiVersion: v1
kind: Service
metadata:
  name: mysql-gyeonggi
spec:
  selector:
    app: mysql-gyeonggi
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 33066
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-gangwon
spec:
  selector:
    app: mysql-gangwon
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30077
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-chungcheong
spec:
  selector:
    app: mysql-chungcheong
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30088
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-gyeongsang
spec:
  selector:
    app: mysql-gyeongsang
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30099
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-jeolla
spec:
  selector:
    app: mysql-jeolla
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30010
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-jeju
spec:
  selector:
    app: mysql-jeju
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30011
  type: NodePort
