apiVersion: v1
kind: Service
metadata:
  name: mysql-gyeonggi
spec:
  selector:
    app: mysql-gyeonggi
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-gangwon
spec:
  selector:
    app: mysql-gangwon
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-chungcheong
spec:
  selector:
    app: mysql-chungcheong
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-gyeongsang
spec:
  selector:
    app: mysql-gyeongsang
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-jeolla
spec:
  selector:
    app: mysql-jeolla
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-jeju
spec:
  selector:
    app: mysql-jeju
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---