apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gyeonggi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gyeonggi
  template:
    metadata:
      labels:
        app: mysql-gyeonggi
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gyeonggi"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-gyeonggi-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gangwon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gangwon
  template:
    metadata:
      labels:
        app: mysql-gangwon
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gangwon"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-gangwon-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-chungcheong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-chungcheong
  template:
    metadata:
      labels:
        app: mysql-chungcheong
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3308
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "chungcheong"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-chungcheong-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gyeongsang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gyeongsang
  template:
    metadata:
      labels:
        app: mysql-gyeongsang
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3309
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gyeongsang"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-gyeongsang-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-jeolla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-jeolla
  template:
    metadata:
      labels:
        app: mysql-jeolla
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3310
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "jeolla"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-jeolla-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-jeju
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-jeju
  template:
    metadata:
      labels:
        app: mysql-jeju
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3311
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-mysql
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "jeju"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-jeju-pvc