apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gyeonggi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gyeonggi
  template:
    metadata:
      labels:
        app: mysql-gyeonggi
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/mysql/*']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-gyeonggi
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gyeonggi"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
              subPath: my.cnf
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-gyeonggi-pvc
        - name: config-volume
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gangwon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gangwon
  template:
    metadata:
      labels:
        app: mysql-gangwon
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/mysql/*']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-gangwon
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gangwon"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
              subPath: my.cnf
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-gangwon-pvc
        - name: config-volume
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-chungcheong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-chungcheong
  template:
    metadata:
      labels:
        app: mysql-chungcheong
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/mysql/*']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-chungcheong
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "chungcheong"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
              subPath: my.cnf
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-chungcheong-pvc
        - name: config-volume
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-gyeongsang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-gyeongsang
  template:
    metadata:
      labels:
        app: mysql-gyeongsang
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/mysql/*']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-gyeongsang
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "gyeongsang"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
              subPath: my.cnf
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-gyeongsang-pvc
        - name: config-volume
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-jeolla
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-jeolla
  template:
    metadata:
      labels:
        app: mysql-jeolla
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/mysql/*']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-jeolla
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "jeolla"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
              subPath: my.cnf
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-jeolla-pvc
        - name: config-volume
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-jeju
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-jeju
  template:
    metadata:
      labels:
        app: mysql-jeju
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'rm -rf /var/lib/mysql/*']
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql-jeju
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: "jeju"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: config-volume
              mountPath: /etc/mysql/conf.d
              subPath: my.cnf
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -u root -p$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-jeju-pvc
        - name: config-volume
          configMap:
            name: mysql-config
            items:
              - key: my.cnf
                path: my.cnf
