apiVersion: apps/v1
kind: Deployment
metadata:
  name: fine-dust-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fine-dust-app
  template:
    metadata:
      labels:
        app: fine-dust-app
    spec:
      containers:
      - name: fine-dust-app
        image: kdonghwan/k8s_finedust_system:latest

        ports:
        - containerPort: 8181
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-gyeonggi:3306/gyeonggi
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_URL_GANGWON
          value: jdbc:mysql://mysql-gangwon:3307/gangwon
        - name: SPRING_DATASOURCE_USERNAME_GANGWON
          value: root
        - name: SPRING_DATASOURCE_PASSWORD_GANGWON
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_URL_CHUNGCHEONG
          value: jdbc:mysql://mysql-chungcheong:3308/chungcheong
        - name: SPRING_DATASOURCE_USERNAME_CHUNGCHEONG
          value: root
        - name: SPRING_DATASOURCE_PASSWORD_CHUNGCHEONG
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_URL_GYEONGSANG
          value: jdbc:mysql://mysql-gyeongsang:3309/gyeongsang
        - name: SPRING_DATASOURCE_USERNAME_GYEONGSANG
          value: root
        - name: SPRING_DATASOURCE_PASSWORD_GYEONGSANG
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_URL_JEOLLA
          value: jdbc:mysql://mysql-jeolla:3310/jeolla
        - name: SPRING_DATASOURCE_USERNAME_JEOLLA
          value: root
        - name: SPRING_DATASOURCE_PASSWORD_JEOLLA
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: SPRING_DATASOURCE_URL_JEJU
          value: jdbc:mysql://mysql-jeju:3311/jeju
        - name: SPRING_DATASOURCE_USERNAME_JEJU
          value: root
        - name: SPRING_DATASOURCE_PASSWORD_JEJU
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MYSQL_ROOT_PASSWORD
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8181
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8181
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fine-dust-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8181
  selector:
    app: fine-dust-app
