apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql_storage_class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
  iops: "3000"
  throughput: "125"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
