name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/kubernetes_particulate_matter_system
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Create .kube directory
        run: mkdir -p ~/.kube

      - name: Setup kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > ~/.kube/config

      - name: Change permissions for kubeconfig
        run: chmod 600 ~/.kube/config

      - name: Update Kubernetes deployment
        run: |
          IMAGE_TAG=${{ github.sha }}
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/kubernetes_particulate_matter_system
          sed -i "s|image: .*/kubernetes_particulate_matter_system:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" ./k8sYamlFile/particulate-matter-deployment.yaml
          kubectl apply -f ./k8sYamlFile/particulate-matter-deployment.yaml
          kubectl rollout status -f ./k8sYamlFile/particulate-matter-deployment.yaml
